/* The following code was generated by JFlex 1.4.3 on 10-4-17 ÏÂÎç12:29 */

package tiger.Parser;
import java_cup.runtime.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 10-4-17 ÏÂÎç12:29 from the specification file
 * <tt>Tiger.flex</tt>
 */
public class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int STRING = 2;
  public static final int YYINITIAL = 0;
  public static final int COMMENT = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2, 2
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\57\1\2\1\0\1\3\1\1\22\0\1\3\1\0\1\6"+
    "\3\0\1\54\1\0\1\40\1\41\1\10\1\47\1\35\1\50\1\46"+
    "\1\7\12\5\1\36\1\37\1\52\1\51\1\53\2\0\32\4\1\42"+
    "\1\56\1\43\1\0\1\4\1\0\1\11\1\14\1\26\1\17\1\15"+
    "\1\24\1\4\1\31\1\30\1\4\1\16\1\21\1\4\1\23\1\20"+
    "\1\32\1\4\1\12\1\22\1\27\1\25\1\33\1\34\1\4\1\13"+
    "\1\4\1\44\1\55\1\45\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\1\1\2\2\1\3\1\4\1\5\1\6\1\7"+
    "\14\3\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\1\30\2\31\1\32\1\33\1\0\2\2\1\34"+
    "\4\3\1\35\1\36\5\3\1\37\1\3\1\40\1\41"+
    "\2\3\1\42\1\43\1\44\1\45\2\0\1\46\1\47"+
    "\1\50\1\51\1\52\1\53\3\3\1\54\1\55\1\56"+
    "\1\57\3\3\1\60\1\3\1\61\1\0\2\3\1\62"+
    "\1\3\1\63\1\64\1\3\1\65\1\66\1\67\1\3"+
    "\1\70\2\3\1\71";

  private static int [] zzUnpackAction() {
    int [] result = new int[106];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\60\0\140\0\220\0\300\0\220\0\360\0\u0120"+
    "\0\220\0\u0150\0\220\0\u0180\0\u01b0\0\u01e0\0\u0210\0\u0240"+
    "\0\u0270\0\u02a0\0\u02d0\0\u0300\0\u0330\0\u0360\0\u0390\0\220"+
    "\0\u03c0\0\220\0\220\0\220\0\220\0\220\0\220\0\220"+
    "\0\220\0\220\0\220\0\220\0\u03f0\0\u0420\0\220\0\220"+
    "\0\u0450\0\u0480\0\220\0\220\0\u04b0\0\u04e0\0\u0510\0\220"+
    "\0\u0540\0\u0570\0\u05a0\0\u05d0\0\360\0\360\0\u0600\0\u0630"+
    "\0\u0660\0\u0690\0\u06c0\0\360\0\u06f0\0\360\0\360\0\u0720"+
    "\0\u0750\0\220\0\220\0\220\0\220\0\u0780\0\u07b0\0\220"+
    "\0\220\0\220\0\220\0\220\0\220\0\u07e0\0\u0810\0\u0840"+
    "\0\360\0\360\0\360\0\360\0\u0870\0\u08a0\0\u08d0\0\360"+
    "\0\u0900\0\220\0\u0930\0\u0960\0\u0990\0\360\0\u09c0\0\360"+
    "\0\360\0\u09f0\0\220\0\360\0\360\0\u0a20\0\360\0\u0a50"+
    "\0\u0a80\0\360";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[106];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\1\5\2\6\1\7\1\10\1\11\1\12\1\13"+
    "\1\14\2\7\1\15\1\16\1\7\1\17\1\20\1\21"+
    "\1\7\1\22\1\23\2\7\1\24\1\25\2\7\1\26"+
    "\1\27\1\30\1\31\1\32\1\33\1\34\1\35\1\36"+
    "\1\37\1\40\1\41\1\42\1\43\1\44\1\45\1\46"+
    "\1\47\1\50\1\4\1\6\1\51\1\52\1\53\3\51"+
    "\1\54\47\51\1\55\1\0\7\6\1\56\1\57\47\6"+
    "\62\0\1\6\61\0\2\7\3\0\24\7\30\0\1\10"+
    "\62\0\1\60\53\0\2\7\3\0\1\7\1\61\22\7"+
    "\27\0\2\7\3\0\1\7\1\62\22\7\27\0\2\7"+
    "\3\0\10\7\1\63\1\7\1\64\11\7\27\0\2\7"+
    "\3\0\7\7\1\65\14\7\27\0\2\7\3\0\13\7"+
    "\1\66\10\7\27\0\2\7\3\0\4\7\1\67\17\7"+
    "\27\0\2\7\3\0\17\7\1\70\4\7\27\0\2\7"+
    "\3\0\7\7\1\71\4\7\1\72\7\7\27\0\2\7"+
    "\3\0\2\7\1\73\4\7\1\74\10\7\1\75\3\7"+
    "\27\0\2\7\3\0\12\7\1\76\1\77\10\7\27\0"+
    "\2\7\3\0\1\100\23\7\27\0\2\7\3\0\20\7"+
    "\1\101\3\7\74\0\1\102\57\0\1\103\1\0\1\104"+
    "\55\0\1\105\6\0\2\51\1\0\3\51\1\0\47\51"+
    "\2\0\2\51\1\53\3\51\1\0\47\51\3\0\3\106"+
    "\1\0\1\107\1\110\14\0\1\111\3\0\1\112\26\0"+
    "\1\113\1\106\10\0\1\114\56\0\1\115\54\0\2\7"+
    "\3\0\1\7\1\116\22\7\27\0\2\7\3\0\4\7"+
    "\1\117\17\7\27\0\2\7\3\0\11\7\1\120\12\7"+
    "\27\0\2\7\3\0\6\7\1\121\15\7\27\0\2\7"+
    "\3\0\16\7\1\122\5\7\27\0\2\7\3\0\10\7"+
    "\1\123\13\7\27\0\2\7\3\0\1\7\1\124\22\7"+
    "\27\0\2\7\3\0\12\7\1\125\11\7\27\0\2\7"+
    "\3\0\21\7\1\126\2\7\27\0\2\7\3\0\4\7"+
    "\1\127\17\7\27\0\2\7\3\0\1\7\1\130\22\7"+
    "\27\0\2\7\3\0\17\7\1\131\4\7\24\0\3\106"+
    "\52\0\1\132\1\106\5\0\1\133\56\0\2\7\3\0"+
    "\1\134\23\7\27\0\2\7\3\0\1\135\23\7\27\0"+
    "\2\7\3\0\4\7\1\136\17\7\27\0\2\7\3\0"+
    "\15\7\1\137\6\7\27\0\2\7\3\0\4\7\1\140"+
    "\17\7\27\0\2\7\3\0\12\7\1\141\11\7\27\0"+
    "\2\7\3\0\10\7\1\142\13\7\30\0\1\143\56\0"+
    "\2\7\3\0\2\7\1\144\21\7\27\0\2\7\3\0"+
    "\5\7\1\145\16\7\27\0\2\7\3\0\16\7\1\146"+
    "\5\7\27\0\2\7\3\0\4\7\1\147\17\7\27\0"+
    "\2\7\3\0\17\7\1\150\4\7\27\0\2\7\3\0"+
    "\7\7\1\151\14\7\27\0\2\7\3\0\12\7\1\152"+
    "\11\7\23\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2736];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\1\11\1\1\1\11\2\1\1\11\1\1\1\11"+
    "\14\1\1\11\1\1\13\11\2\1\2\11\2\1\2\11"+
    "\1\0\2\1\1\11\21\1\4\11\2\0\6\11\14\1"+
    "\1\11\1\0\7\1\1\11\7\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[106];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
	StringBuffer string = new StringBuffer();
	int commentCount;
	/* To create a new java_cup.runtime.Symbol with information about
	   the current token, the token will have no value in this
	   case. */
	private Symbol symbol(int type) {
		return new Symbol(type, yyline, yycolumn);
	}
	
	/* Also creates a new java_cup.runtime.Symbol with information
	   about the current token, but this object has a value. */
	private Symbol symbol(int type, Object value) {
		return new Symbol(type, yyline, yycolumn, value);
	}


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 130) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 30: 
          { return symbol(sym.OF);
          }
        case 58: break;
        case 31: 
          { return symbol(sym.TO);
          }
        case 59: break;
        case 12: 
          { return symbol(sym.RPAREN);
          }
        case 60: break;
        case 1: 
          { throw new RuntimeException(" Illegal character <" + yytext() + ">");
          }
        case 61: break;
        case 3: 
          { return symbol(sym.ID, yytext());
          }
        case 62: break;
        case 22: 
          { return symbol(sym.GT);
          }
        case 63: break;
        case 44: 
          { return symbol(sym.END);
          }
        case 64: break;
        case 40: 
          { string.append('\t');
          }
        case 65: break;
        case 21: 
          { return symbol(sym.LT);
          }
        case 66: break;
        case 15: 
          { return symbol(sym.LBRACE);
          }
        case 67: break;
        case 5: 
          { string.setLength(0); yybegin(STRING);
          }
        case 68: break;
        case 23: 
          { return symbol(sym.AND);
          }
        case 69: break;
        case 53: 
          { int val = Integer.parseInt(yytext().substring(1, 4));
		if(val > 255) throw new RuntimeException("Illegal string with \\ddd"); else string.append((char)val);
          }
        case 70: break;
        case 34: 
          { return symbol(sym.ASSIGN);
          }
        case 71: break;
        case 41: 
          { string.append('\\');
          }
        case 72: break;
        case 18: 
          { return symbol(sym.PLUS);
          }
        case 73: break;
        case 26: 
          { throw new RuntimeException("Unterminated string at end of line");
          }
        case 74: break;
        case 54: 
          { return symbol(sym.ARRAY);
          }
        case 75: break;
        case 51: 
          { return symbol(sym.TYPE);
          }
        case 76: break;
        case 4: 
          { return symbol(sym.NUM, new Integer(yytext()));
          }
        case 77: break;
        case 29: 
          { return symbol(sym.DO);
          }
        case 78: break;
        case 7: 
          { return symbol(sym.TIMES);
          }
        case 79: break;
        case 50: 
          { return symbol(sym.ELSE);
          }
        case 80: break;
        case 38: 
          { string.append('\"');
          }
        case 81: break;
        case 36: 
          { return symbol(sym.NEQ);
          }
        case 82: break;
        case 13: 
          { return symbol(sym.LBRACK);
          }
        case 83: break;
        case 9: 
          { return symbol(sym.COLON);
          }
        case 84: break;
        case 52: 
          { return symbol(sym.THEN);
          }
        case 85: break;
        case 48: 
          { return symbol(sym.VAR);
          }
        case 86: break;
        case 56: 
          { return symbol(sym.WHILE);
          }
        case 87: break;
        case 55: 
          { return symbol(sym.BREAK);
          }
        case 88: break;
        case 33: 
          { return symbol(sym.IF);
          }
        case 89: break;
        case 11: 
          { return symbol(sym.LPAREN);
          }
        case 90: break;
        case 49: 
          { /* nothing to do */
          }
        case 91: break;
        case 27: 
          { yybegin(YYINITIAL);return symbol(sym.STRING, string.toString());
          }
        case 92: break;
        case 24: 
          { return symbol(sym.OR);
          }
        case 93: break;
        case 32: 
          { return symbol(sym.IN);
          }
        case 94: break;
        case 20: 
          { return symbol(sym.EQ);
          }
        case 95: break;
        case 16: 
          { return symbol(sym.RBRACE);
          }
        case 96: break;
        case 47: 
          { return symbol(sym.FOR);
          }
        case 97: break;
        case 45: 
          { return symbol(sym.LET);
          }
        case 98: break;
        case 39: 
          { string.append('\n');
          }
        case 99: break;
        case 10: 
          { return symbol(sym.SEMI);
          }
        case 100: break;
        case 46: 
          { return symbol(sym.NIL);
          }
        case 101: break;
        case 25: 
          { string.append(yytext());
          }
        case 102: break;
        case 19: 
          { return symbol(sym.MINUS);
          }
        case 103: break;
        case 42: 
          { commentCount++;
          }
        case 104: break;
        case 43: 
          { commentCount--;if (commentCount==0) {yybegin(YYINITIAL);}
          }
        case 105: break;
        case 37: 
          { return symbol(sym.GE);
          }
        case 106: break;
        case 57: 
          { return symbol(sym.FUNCTION);
          }
        case 107: break;
        case 6: 
          { return symbol(sym.DIVIDE);
          }
        case 108: break;
        case 8: 
          { return symbol(sym.COMMA);
          }
        case 109: break;
        case 35: 
          { return symbol(sym.LE);
          }
        case 110: break;
        case 28: 
          { commentCount = 1; yybegin(COMMENT);
          }
        case 111: break;
        case 14: 
          { return symbol(sym.RBRACK);
          }
        case 112: break;
        case 17: 
          { return symbol(sym.DOT);
          }
        case 113: break;
        case 2: 
          { 
          }
        case 114: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { 	{
		if(yystate() == STRING)
		{
			throw new RuntimeException("Unclosed string constant " + "at end of file");
		}
		if(yystate() == COMMENT)
		{
			throw new RuntimeException("Unclosed comment " + "at end of file");
		}
		return symbol(sym.EOF);
	}
 }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
